---
# Snap installs
- name: (SNAP) Install General Tools
  community.general.snap:
    name: "{{ item }}"
  with_items:
    - "kompose"

- name: Install helm
  ansible.builtin.command: snap install helm --classic
  become: true
  become_user: root
