---
version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ~/appdata/heimdall/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - ~/appdata/jellyin/library:/config
      - ~/appdata/jellyin/tvseries:/data/tvshows
      - ~/appdata/jellyin/movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped

  yacht:
    image: selfhostedpro/yacht:latest
    container_name: yacht
    volumes:
      - ~/appdata/yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
    restart: unless-stopped

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ~/appdata/deluge/config:/config
      - ~/Downloads/:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ~/appdata/radarr/config:/config
      - ~/appdata/jellyin/movies:/movies
      - ~/Downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ~/appdata/sonarr/config:/config
      - ~/appdata/jellyin/tvseries:/tv
      - ~/Downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  homeassistant:
    image: lscr.io/linuxserver/homeassistant
    container_name: homeassistant
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ~/appdata/homeassistant:/config
    ports:
      - 8123:8123
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma:alpine
    container_name: uptime-kuma
    volumes:
      - ~/appdata/uptime-kuma:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    volumes:
      - ~/appdata/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9443:9443
    restart: unless-stopped

  #pihole:
  #  image: pihole/pihole:latest
  #  container_name: pihole
  #  environment:
  #    TZ: America/Chicago
  #    WEBPASSWORD: asdf
  #  volumes:
  #    - ~/appdata/pi-hole/:/etc/pihole
  #    - ~/appdata/pi-hole/dns-masq.d/:/etc/dnsmasq.d
  #
  #  ports:
  #    - 53:53/tcp
  #    - 53:53/udp
  #   - 8081:80/tcp

  #  restart: unless-stopped

  #nut-upsd:
  #  image: instantlinux/nut-upsd
  #  ports:
  #    - 3493:3493
  #  environment:
  #    - SERIAL=abcdef123456
  #  secrets:
  #    - nut-upsd-password
  #  devices:
  #    - /dev/usb/hiddev0:/dev/usb/hiddev0
  #  privileged: true
  #  restart: unless-stopped

  #cloudflare-ddns:
  #  image: oznu/cloudflare-ddns:latest
  #  restart: always
  #  environment:
  #    - API_KEY=xxxxxxx
  #    - ZONE=example.com
  #    - SUBDOMAIN=subdomain
  #    - PROXIED=false

  #gitlab:
  #  image: 'gitlab/gitlab-ee:latest'
  #  restart: always
  #  hostname: 'gitlab.example.com'
  #  environment:
  #    GITLAB_OMNIBUS_CONFIG: |
  #      external_url 'https://gitlab.example.com'
  # Add any other gitlab.rb configuration here, each on its own line
  #  ports:
  #    - '80:80'
  #    - '443:443'
  #    - '22:22'
  #  volumes:
  #    - '$GITLAB_HOME/config:/etc/gitlab'
  #    - '$GITLAB_HOME/logs:/var/log/gitlab'
  #    - '$GITLAB_HOME/data:/var/opt/gitlab'
  #  shm_size: '256m'

  #image: nginx
  #  volumes:
  #  - ./templates:/etc/nginx/templates
  #  ports:
  #  - "8080:80"
  #  environment:
  #  - NGINX_HOST=foobar.com
  #  - NGINX_PORT=80