apiVersion: v1
kind: Pod
metadata:
  name: prometheus-example
  labels:
    app: prometheus
spec:
  containers:
    - name: prometheus
      image: prometheus
      ports:
        - containerPort: 80
          name: "prometheus-http"