apiVersion: v1
kind: Service
metadata:
  name: prometheus-example
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: 9090
      targetPort: prometheus-http
  selector:
    app: prometheus
