---

- name: Install k3s on servers
  import_tasks: server.yml
  when: inventory_hostname in groups['servers']

- name: Install k3s on agents
  import_tasks: agent.yml
  when: inventory_hostname in groups['agents']
