---
- name: Install k3s on servers
  ansible.builtin.import_tasks: server.yml # yamllint disable-line
  when: inventory_hostname in groups['servers']

- name: Start VM
  ansible.builtin.import_tasks: start_vm.yml # yamllint disable-line
  when: inventory_hostname in groups['agents']
