---

- name: Install k3s on servers
  import_tasks: server.yml
  when: inventory_hostname in groups['servers']

- name: Start VM
  import_tasks: start_vm.yml
  when: inventory_hostname in groups['agents']
