---
k3s_version: v1.22.3+k3s1
ansible_user: "dcard"
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['servers'][0]]['ansible_host'] | default(groups['servers'][0]) }}"

# k3s_token is required  servers can talk together securely
# this token should be alpha numeric only
k3s_token: "some-SUPER-DEDEUPER-secret-pass word"

extra_server_args: ""
extra_agent_args: ""
