---
k3s_version: v1.22.3+k3s1
ansible_user: "dcard"
systemd_dir: /etc/systemd/system
server_ip: "{{ hostvars[groups['servers'][0]]['ansible_host'] | default(groups['servers'][0]) }}"

# k3s_token is required  servers can talk together securely
# this token should be alpha numeric only
k3s_token: "eyJhbGciOiJSUzI1NiIsImtpZCI6IlVNZG44MXQxZnRib28tS0RHMTYyZ1dqTTlnQWE2QjVyMGd4VDZCSkdDRUEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4tY2w3a2MiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImU4ODFmNDVlLTMxNGUtNGUyOC04YmYxLWNiYjI5ODFlNWM2MyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmRlZmF1bHQifQ.ZgFB3OUfxoo1l_7DUBmyIAjyysVrkD7DdnbP_DDBxJ_EqDNnuAkazyv8saYU6SCT621OgCJPH-h2l1O-dwodpUSNHdjSC0pGt2r7hg9pCSC3g-8Y8xeIYwaOh50fWJv-Zqk_1qIvY25jj-UPeMZel-xEG8IPRlpZFi6WdoXwzEMKzgUqatzfcH4Tl_eZGbRuacYpJswiJSjd3Ut626LER0HEB7NtlQtMZOjTTWORorrxdbmIYAxufBxIAAYX_ivTxPTMt_QMu7aqh2qYvrO7IGRHte0ZCWCAA_WtsqNET69W_J0ay2GrkhwLcJk7L4C9tLqq2yQn_9Rtg-RwprsmxQ"

extra_server_args: ""
extra_agent_args: ""