---
##########################
##########################
## Ansible Linter rules ##
##########################
##########################

#############################
# Exclude paths from linter #
#############################
# exclude_paths:

########################
# Make output parsable #
########################
parseable: true

#######################
# Set output to quiet #
#######################
quiet: true

#####################
# Path to rules dir #
#####################
# rulesdir:

################
# Tags to skip #
################
skip_list:
  - 'octal-values'
  - 'no-changed-when' # False positives for running command shells
  - '204'  # Allow string length greater than 160 chars
  - k3s_install
  - proxmox
#  - 'empty-string-compare'  # Allow compare to empty string
#  - 'no-changed-when'
#  - 'command-instead-of-module'  # Allow git commands for push, add, etc...
#  - 'command-instead-of-shell'  # Allow use of shell when you want
#  - 'no-handler'  # Allow step to run like handler
#  - 'unnamed-task' # Allow tasks without a name
#  - 'yaml' # Disable YAML linting since it's done by yamllint

##################
# Tags to follow #
##################
# tags:

#############
# Use rules #
#############
use_default_rules: false

#################
# Set verbosity #
#################
verbosity: 1