apiVersion: v1
kind: Pod
metadata:
  name: grafana-example
  labels:
    app: grafana
spec:
  containers:
    - name: grafana
      image: grafana
      ports:
        - containerPort: 80
          name: "grafana-http"
