---

- name: Install pre-requisites on Bare Metal
  hosts: localhost
  become: true
  connection: local
  roles:
    - installs-apt
    - installs-snap
    - installs-pip
    - metal

- name: Install Docker on Bare Metal and Cluster
  hosts: k3s_cluster, localhost
  become: true
  roles:
    - docker-install

- name: Gerneate Docker container bind mounts
  hosts: localhost
  become: true
  roles:
    - docker-mkdir