---
- name: Install pre-requisites on Bare Metal
  hosts: localhost
  become: true
  connection: local
  roles:
    - installs_apt
    - installs_snap
    - installs_pip
    - metal

- name: Install Docker on Bare Metal and Cluster
  hosts: k3s_cluster, localhost
  become: true
  roles:
    - docker_install

- name: Gerneate Docker container bind mounts
  hosts: localhost
  become: true
  roles:
    - docker_mkdir
