---
- name: Clone Proxmox VM
  hosts: proxmox
  vars_prompt:
    - name: password
      prompt: What is your proxmox password?

    - name: vm_names_csv
      prompt: "Please specify the server names, separated by commas (NO SPACES)"
      private: false

    - name: template
      prompt: What template would you like to use?
      private: false

  tasks:
    - ansible.builtin.set_fact:
        vm_names: "{{ vm_names_csv.split(',') }}"

    - name: Clone VM
      proxmox_kvm:
        api_user: root@pam
        api_password: "{{ password }}"
        api_host: 192.168.122.20
        clone: "{{ template }}"
        name: "{{ item }}"
        node: proxmox
        storage: local-lvm
        format: qcow2
        timeout: 500
      loop: "{{ vm_names }}"

    - name: Pause for 5 seconds before starting
      ansible.builtin.pause:
        seconds: 3

    - name: Start VM
      proxmox_kvm:
        api_user: root@pam
        api_password: "{{ password }}"
        api_host: 192.168.122.20
        name: "{{ item }}"
        node: proxmox
        state: started
      loop: "{{ vm_names }}"
