---
- name: Install k3s on servers
  ansible.builtin.include_tasks: server.yml # yamllint disable-line
  when: inventory_hostname in groups['servers']

- name: Install k3s on nodes
  ansible.builtin.include_tasks: node.yml # yamllint disable-line
  when: inventory_hostname in groups['nodes']
