---
- name: Install k3s on servers
  ansible.builtin.import_tasks: ansible/roles/k3s_install/tasks/server.yml
  when: inventory_hostname in groups['servers']

- name: Install k3s on nodes
  ansible.builtin.import_tasks: ansible/roles/k3s_install/tasks/node.yml
  when: inventory_hostname in groups['nodes']
