---
- name: Install k3s on servers
  ansible.builtin.include_tasks: server.yml
  when: inventory_hostname in groups['servers']

- name: Install k3s on nodes
  ansible.builtin.include_tasks: node.yml
  when: inventory_hostname in groups['nodes']
