---
- name: Copy K3s node template file
  template:
    src: "k3s.node.j2"
    dest: "{{ systemd_dir }}/k3s-node.service"
    owner: root
    group: root
    mode: 0755

- name: Enable and check K3s-node service
  systemd:
    name: k3s-node
    daemon_reload: yes
    state: restarted
    enabled: yes
